
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "strategy_optimizer"
version = "0.1"
dependencies = [
    "pydantic",
    "pyarrow",
    "sqlalchemy",
    "ccxt",
    "pyyaml",
    "numpy",
    "pandas",
    "scipy",
    "requests",
    "python-dotenv",
    "fastapi",
    "uvicorn",
    "prometheus-client",
    "boto3",
    "openai",
    "pytest",
    "supabase"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
